[Feature] modal 커스텀 훅 생성
Team-TMB/client pull request #45
Opened 2024-02-16 16:16 UTC by doitidey

### 📌 개요

closed #44
모달 커스텀 훅을 작성합니다.

### ✅ 작업내용

- zustand를 통해 전역으로 모달의 상태를 관리합니다.
- 커스텀 훅을 제작하여 open, close를 용이하게 합니다.
- modal 기본 컴포넌트 내에서 틀 스타일링은 완료되었습니다.
    - 닫기 버튼과 close 로직 처리 되어있습니다. 
    - 배경 어둡게 처리해두었습니다.

### 📝 공유사항

openModal 사용시
- 내용이 될 모달의 컴포넌트 자체를 content로 보내주시면 됩니다.

문제사항!
<img width="1118" alt="스크린샷 2024-02-17 오전 1 14 30" src="https://github.com/Team-TMB/client/assets/128357188/73f99eaf-1ed4-4f1c-af50-28c006c7abda">
- 헤더가 모달보다 앞에 있어 수정이 필요합니다.
    - 둘 다 sticky이고, z-index를 헤더보다 모달에 더 큰 숫자를 부여해도 상황이 같습니다.

2024-02-17 04:26 UTC, pildrums requested changes
코멘트 남겨드렸어요~!!

2024-02-17 04:26 UTC, pildrums commented on src/components/common/Modal.scss
> +.modal-block {
fixed 속성 들어갔으니까 top:0 left:0 속성도 추가해보세요 헤더도 덮을겁니다

2024-02-17 05:30 UTC, pildrums requested changes

2024-02-17 05:30 UTC, pildrums commented on src/components/common/Modal.tsx
> +              <Image
잘하셨어요~! 여기서 span 태그를 이용해서 close 버튼을 만들어보는 것도 좋은 방법일거 같고, react-icons 라이브러리를 활용해서 만드는 것도 좋은 방법이라 생각합니다~!

2024-02-18 14:22 UTC, doitidey commented on src/components/common/Modal.tsx
> +              <Image
close 버튼은 figma 설계도대로 디자이너 분들이 만들어두신 아이콘 svg 활용하여 버튼 만들어 두었습니다. 캠쳐화면 확인해주세용 :)

2024-02-18 14:25 UTC, doitidey commented on src/components/common/Modal.scss
> +.modal-block {
말씀주신대로 하니 해결되었습니다! 감사합니다 👍

2024-02-18 14:26 UTC, merged